export const openpayConfig = {
	OPENPAY_MERCHANT_ID: 'YOUR_OPENPAY_MERCHANT_ID_HERE',
	OPENPAY_PUBLIC_KEY: 'YOUR_OPENPAY_PUBLIC_KEY_HERE',
	OPENPAY_PRIVATE_KEY: 'YOUR_OPENPAY_PRIVATE_KEY_HERE',
	OPENPAY_SANDBOX_MODE: 'YOUR_OPENPAY_SANDBOX_MODE_HERE (BOOLEAN)',
	OPENPAY_PRODUCTION_MODE: 'YOUR_OPENPAY_PRODUCTION_MODE_HERE (BOOLEAN)',
	OPENPAY_SANDBOX_URL: "YOUR_OPENPAY_SANDBOX_URL_HERE"
};
