name: Deploy Angular App to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Create environment config files
      run: |
        mkdir -p src/environment

        cat <<EOF > src/environment/firebase.config.ts
        export const firebaseConfig = {
          apiKey: "${{ secrets.FIREBASE_API_KEY }}",
          authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
          storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
          messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
          appId: "${{ secrets.FIREBASE_APP_ID }}",
          measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
        };
        EOF

        cat <<EOF > src/environment/functions.config.ts
        export const agregarUsuarioUrl = "${{ secrets.FUNC_CREAR_USUARIO_URL }}";
        export const eliminarUsuarioUrl = "${{ secrets.FUNC_ELIMINAR_USUARIO_URL }}";
        export const checkpagostatus = "${{ secrets.FUNC_CHECKPAGO_URL }}";
        export const processPaymentURL = "${{ secrets.FUNC_PAGO_URL }}";
        EOF

        cat <<EOF > src/environment/openpay.config.ts
        export const openpayConfig = {
          OPENPAY_PUBLIC_KEY: "${{ secrets.OPENPAY_PUBLIC_KEY }}",
          OPENPAY_MERCHANT_ID: "${{ secrets.OPENPAY_MERCHANT_ID }}",
          OPENPAY_PRODUCTION_MODE: ${{
            secrets.OPENPAY_PRODUCTION_MODE == 'true' && 'true' || 'false'
          }}
          OPENPAY_SANDBOX_MODE : ${{
            secrets.OPENPAY_SANDBOX_MODE == 'true' && 'true' || 'false'
          }}
        };
        EOF

    - name: Build Angular App
      run: npm run build --prod

    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/v001-Tres-Islas/browser
        server-dir: ${{ secrets.FTP_TARGET_DIR }}/

